spring:
  application:
    name: spring-ai-alibaba-qwq-chat-client-example
  ai:
    dashscope:
      api-key: sk-7f377d9318cc4b1eb348b5e775003166
      chat:
        options:
          model: qwen-plus
      embedding:
        options:
          model: text-embedding-v2
    # MCP Client Configuration
    mcp:
      client:
        stdio:
          servers-configuration: classpath:mcp-server.json
    vectorstore:
      pgvector:
        index-type: HNSW
        dimensions: 1536
        distance-type: COSINE_DISTANCE
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
  datasource:
    url: jdbc:postgresql://rm-cn-h964po5pe00017to.rwlb.rds.aliyuncs.com:5432/health_ai_agent
    username: my_user
    password: Lixuefei123


